# Generated by Django 6.0.3 on 2026-03-24 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(upload_to='coordinators/')),
                ('role', models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty')], max_length=20)),
                ('contact_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(help_text="E.g., 'Inauguration', 'Robo Wars'", max_length=100)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_link', models.URLField(help_text='Paste your Google Form URL here', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Check to make this the active link')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Technical', 'Technical'), ('Non-Technical', 'Non-Technical')], max_length=20)),
                ('description', models.TextField()),
                ('rules', models.TextField()),
                ('start_time', models.TimeField(help_text='Format: HH:MM:SS (e.g., 09:30:00)')),
                ('end_time', models.TimeField(help_text='Format: HH:MM:SS (e.g., 15:00:00)')),
                ('max_members', models.PositiveIntegerField(default=1, help_text='Max participants per team')),
                ('coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='sympo.coordinator')),
            ],
        ),
    ]
